// =========================================
// TXPWR.h is auto-generated by tplmt2h.pl.
// =========================================

#ifndef __H
#define __H
#define _MAX 
unsigned char *data__array[]={
	data_,
};
unsigned char *data__array_end[]={
	data_+sizeof(data_),
};
#endif